testfile/config/routes.rb
Rails.application.routes.draw do

   resources :sounds, :subs, :kicks, :snares, :hats, :cymbals, :claps, only: [:index, :new, :create, :destroy]
   root "sounds#index"

end

# CarrierWaveExample::Application.routes.draw do

#    resources :resumes, only: [:index, :new, :create, :destroy]
#    root "resumes#index"
# end

testfile/app/models/clap.rb
class Clap < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/cymbal.rb
class Cymbal < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/hat.rb
class Hat < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/kick.rb
class Kick < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/snare.rb
class Snare < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/sound.rb
class Sound < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/models/sub.rb
class Sub < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # tells rails to use this uploader for this model
  validates :name, presence: true # makes sure the owner's name is present
end

testfile/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

testfile/app/controllers/claps_controller.rb
class ClapsController < ApplicationController
  require 'carrierwave'

   def index
      @claps = Clap.all
   end

   def new
      @clap = Clap.new
   end

   def create
      @clap = Clap.new(claps_params)

      if @clap.save
         redirect_to claps_path, notice: "The sound #{@clap.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @clap = Clap.find(params[:id])
      @clap.destroy
      redirect_to claps_path, notice:  "The sound #{@clap.name} has been deleted."
   end

   private
      def claps_params
      params.require(:clap).permit(:name, :attachment)
   end

end

testfile/app/controllers/cymbals_controller.rb
class CymbalsController < ApplicationController
  require 'carrierwave'

   def index
      @cymbals = Cymbal.all
   end

   def new
      @cymbal = Cymbal.new
   end

   def create
      @cymbal = Cymbal.new(cymbals_params)

      if @cymbal.save
         redirect_to cymbals_path, notice: "The sound #{@cymbal.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @cymbal = Cymbal.find(params[:id])
      @cymbal.destroy
      redirect_to cymbals_path, notice:  "The sound #{@cymbal.name} has been deleted."
   end

   private
      def cymbals_params
      params.require(:cymbal).permit(:name, :attachment)
   end

end

testfile/app/controllers/hats_controller.rb
class HatsController < ApplicationController
  require 'carrierwave'

   def index
      @hats = Hat.all
   end

   def new
      @hat = Hat.new
   end

   def create
      @hat = Hat.new(hats_params)

      if @hat.save
         redirect_to hats_path, notice: "The sound #{@hat.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @hat = Hat.find(params[:id])
      @hat.destroy
      redirect_to hats_path, notice:  "The sound #{@hat.name} has been deleted."
   end

   private
      def hats_params
      params.require(:hat).permit(:name, :attachment)
   end

end

testfile/app/controllers/kicks_controller.rb
class KicksController < ApplicationController
  require 'carrierwave'

   def index
      @kicks = Kick.all
   end

   def new
      @kick = Kick.new
   end

   def create
      @kick = Kick.new(kicks_params)

      if @kick.save
         redirect_to kicks_path, notice: "The sound #{@kick.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @kick = Kick.find(params[:id])
      @kick.destroy
      redirect_to kicks_path, notice:  "The sound #{@kick.name} has been deleted."
   end

   private
      def kicks_params
      params.require(:kick).permit(:name, :attachment)
   end

end

testfile/app/controllers/snares_controller.rb
class SnaresController < ApplicationController
  require 'carrierwave'

   def index
      @snares = Snare.all
   end

   def new
      @snare = Snare.new
   end

   def create
      @snare = Snare.new(snares_params)

      if @snare.save
         redirect_to snares_path, notice: "The sound #{@snare.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @snare = Snare.find(params[:id])
      @snare.destroy
      redirect_to kicks_path, notice:  "The sound #{@snare.name} has been deleted."
   end

   private
      def snares_params
      params.require(:snare).permit(:name, :attachment)
   end

end

testfile/app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  require 'carrierwave'

   def index
      @sounds = Sound.all
   end

   def new
      @sound = Sound.new
   end

   def create
      @sound = Sound.new(sound_params)

      if @sound.save
         redirect_to sounds_path, notice: "The sound #{@sound.name} has been uploaded."
      else
         render "new"
      end

   end

   def destroy
      @sound = Sound.find(params[:id])
      @sound.destroy
      redirect_to sounds_path, notice:  "The sound #{@sound.name} has been deleted."
   end

   private
      def sound_params
      params.require(:sound).permit(:name, :attachment)
   end

end

testfile/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  require 'carrierwave'

   def index
      @subs = Sub.all
   end

   def new
      @sub = Sub.new
   end

   def create
      @sub = Sub.new(subs_params)

      if @sub.save
         redirect_to subs_path, notice: "The sound #{@sub.name} has been uploaded."
      else
         render "new"
      end

   end
   def destroy
      @sub = Sub.find(params[:id])
      @sub.destroy
      redirect_to subs_path, notice:  "The sound #{@sub.name} has been deleted."
   end

   private
      def subs_params
      params.require(:sub).permit(:name, :attachment)
   end

end

testfile/app/helpers/application_helper.rb
module ApplicationHelper
end

testfile/app/helpers/claps_helper.rb
module ClapsHelper
end

testfile/app/helpers/cymbals_helper.rb
module CymbalsHelper
end

testfile/app/helpers/hats_helper.rb
module HatsHelper
end

testfile/app/helpers/kicks_helper.rb
module KicksHelper
end

testfile/app/helpers/snares_helper.rb
module SnaresHelper
end

testfile/app/helpers/sounds_helper.rb
module SoundsHelper
end

testfile/app/helpers/subs_helper.rb
module SubsHelper
end

testfile/app/views/claps/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search claps by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
 <!--    <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_clap_path, class: "btn btn-primary" %>
<br>



<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @claps.each do |clap| %>
         <tr>
            <td><%= clap.name %></td>
            <td><%= link_to "Play", clap.attachment_url %></td>
            <td><a href=<%=clap.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  clap, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{clap.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/claps/new.html.erb
<% if !@clap.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @clap.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>

<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

<div class="new-middle">
<h3>New Clap</h3>
   <%= form_for @clap, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/cymbals/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
      <div class = "alert alert-info">
         <%= flash[:notice] %>
      </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search cymbals by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
<!--     <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_cymbal_path, class: "btn btn-primary" %>
<br>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @cymbals.each do |cymbal| %>
         <tr>
            <td><%= cymbal.name %></td>
            <td><%= link_to "Play", cymbal.attachment_url %></td>
            <td><a href=<%=cymbal.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  cymbal, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{cymbal.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/cymbals/new.html.erb
<% if !@cymbal.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @cymbal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

<div class="new-middle">
<h3>New Cymbal</h3>
   <%= form_for @cymbal, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/hats/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
      <div class = "alert alert-info">
         <%= flash[:notice] %>
      </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search hi-hats by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
<!--     <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_hat_path, class: "btn btn-primary" %>
<br>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @hats.each do |hat| %>
         <tr>
            <td><%= hat.name %></td>
            <td><%= link_to "Play", hat.attachment_url %></td>
            <td><a href=<%=hat.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  hat, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{hat.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/hats/new.html.erb
<% if !@hat.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @hat.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

<div class="new-middle">
<h3>New Hi-Hat</h3>
   <%= form_for @hat, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/kicks/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
      <div class = "alert alert-info">
         <%= flash[:notice] %>
      </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search kicks by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
<!--     <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_kick_path, class: "btn btn-primary" %>
<br>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @kicks.each do |kick| %>
         <tr>
            <td><%= kick.name %></td>
            <td><%= link_to "Play", kick.attachment_url %></td>
            <td><a href=<%=kick.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  kick, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{kick.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/kicks/new.html.erb
<% if !@kick.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @kick.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

<div class = "new-middle">
<h3>New Kick</h3>
   <%= form_for @kick, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/snares/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search snares by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
<!--     <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_snare_path, class: "btn btn-primary" %>
<br>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @snares.each do |snare| %>
         <tr>
            <td><%= snare.name %></td>
            <td><%= link_to "Play", snare.attachment_url %></td>
            <td><a href=<%=snare.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  snare, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{snare.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/snares/new.html.erb
<% if !@snare.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @snare.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

<div class="new-middle">
<h3>New Snare</h3>
   <%= form_for @snare, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>

testfile/app/views/sounds/new.html.erb
<% if !@sound.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @sound.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<a href="/sounds">Home</a>
<a href="/subs">808s</a>
<a href="/kicks">Kicks</a>
<a href="/snares">Snares</a>
<a href="/hats">Hats</a>
<a href="/cymbals">Cymbals</a>
<a href="/claps">Claps</a>

<div class = "well">
   <%= form_for @sound, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

testfile/app/views/subs/index.html.erb
<div class="container">
   <nav>
      <div class="nav-wrapper">
         <a href="/sounds" class="brand-logo" >Home</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
            <a href="/subs">808s</a>
            <a href="/kicks">Kicks</a>
            <a href="/snares">Snares</a>
            <a href="/hats">Hats</a>
            <a href="/cymbals">Cymbals</a>
            <a href="/claps">Claps</a>
         </ul>
      </div>
   </nav>

   <% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
   <% end %>

<div class="middle">

  <form id="search">
    <h1>Search 808s by name:</h1>
    <input type="search" id="search-keyword">
    <select id="search-type">
      <option id="artist" value="artist">Search by Artist</option>
      <option id="track" value="track">Search by Track</option>
    </select>
<!--   <input id="submit" type="submit" value="Submit"> -->
  </form>
  <br>

   <%= link_to "New Sound", new_sub_path, class: "btn btn-primary" %>
<br>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Sound</th>
         <th>Play Sound</th>
         <th>Download Sound</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @subs.each do |sub| %>
         <tr>
            <td><%= sub.name %></td>
            <td><%= link_to "Play", sub.attachment_url %></td>
            <td><a href=<%=sub.attachment_url%> download>Download</a></td>
            <td><%= button_to "Delete",  sub, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{sub.name}?" %></td>
         </tr>
      <% end %>
   </tbody>
</table>
</div>

<footer class="page-footer">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="copyright">
            © 2016 Copyright SampleSpace
            </div>
         </div>
</footer>
</div>